version: '3'
services:
  postgres:
    image: postgres:10-alpine
    container_name: petDb
    environment:
      - POSTGRES_USER=shelter
      - POSTGRES_DB=shelter
      - POSTGRES_PASSWORD=shelter
    ports:
      - '5432:5432'
    expose:
      - '5432'
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: petEs01
    environment:
      - node.name=es01
      - discovery.type=single-node
    ports:
    - 9200:9200
volumes:
  pgadmindata:
